### PR TITLE
Added gibberish

### PR DESCRIPTION
**Pull request by AlexOBarnes**
Added gibberish to readme

### CODE REVIEW

**Comment by Ruyzambrano** [comment]
Approved

**Review by Ruyzambrano — DISMISSED** [review]

**Review by paulauus — APPROVED** [review]
Good stuff.

**Review by Ruyzambrano — APPROVED** [review]

**Review by indiah444 — APPROVED** [review]
A very good comment

**Review by ayahusseini — COMMENTED** [review]
approved

**Pull request merged**
